import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Zap, BookOpen, Trophy, ChevronRight, Target, Keyboard, TrendingUp, Star, ArrowRight } from 'lucide-react';

// Animated typing preview component
function TypingPreview() {
  const text = "The quick brown fox jumps over the lazy dog";
  const [typed, setTyped] = useState(0);
  const intervalRef = useRef<ReturnType<typeof setInterval>>();

  useEffect(() => {
    intervalRef.current = setInterval(() => {
      setTyped(prev => {
        if (prev >= text.length) {
          clearInterval(intervalRef.current);
          setTimeout(() => setTyped(0), 1500);
          return prev;
        }
        return prev + 1;
      });
    }, 60);
    return () => clearInterval(intervalRef.current);
  }, [typed === 0]);

  return (
    <div className="font-mono text-sm sm:text-base leading-relaxed select-none pointer-events-none">
      {text.split('').map((char, i) => (
        <span
          key={i}
          className={`transition-colors duration-75 ${
            i < typed ? 'text-brand-accent' :
            i === typed ? 'text-brand-primary border-b-2 border-brand-primary' :
            'text-brand-muted'
          }`}
        >
          {char}
        </span>
      ))}
    </div>
  );
}

// Stat counter animation
function CountUp({ to, suffix = '' }: { to: number; suffix?: string }) {
  const [count, setCount] = useState(0);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      if (!entry.isIntersecting) return;
      observer.disconnect();
      let start = 0;
      const step = to / 60;
      const timer = setInterval(() => {
        start += step;
        if (start >= to) { setCount(to); clearInterval(timer); }
        else setCount(Math.round(start));
      }, 16);
    }, { threshold: 0.3 });
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [to]);

  return (
    <div ref={ref} className="font-black text-2xl sm:text-3xl tabular-nums font-mono text-brand-text">
      {count.toLocaleString()}{suffix}
    </div>
  );
}

const FEATURES = [
  {
    icon: Zap,
    title: 'Real-time Speed Test',
    desc: 'Live WPM, CPM, and accuracy tracking as you type. Choose from 15 seconds to 10 minutes.',
    color: 'text-brand-primary',
    bg: 'bg-brand-primary/10 border-brand-primary/20',
    link: '/tests',
  },
  {
    icon: BookOpen,
    title: 'Structured Lessons',
    desc: 'Build muscle memory from scratch with a guided, interactive curriculum designed for all levels.',
    color: 'text-brand-secondary',
    bg: 'bg-brand-secondary/10 border-brand-secondary/20',
    link: '/learn',
  },
  {
    icon: Target,
    title: 'AI-Powered Analysis',
    desc: 'Identify your weak keys and problem patterns. Get personalized practice sessions generated by AI.',
    color: 'text-brand-accent',
    bg: 'bg-brand-accent/10 border-brand-accent/20',
    link: '/tests',
  },
  {
    icon: Trophy,
    title: 'Global Leaderboard',
    desc: 'Compete with typists around the world. Earn badges, climb leagues, and celebrate your progress.',
    color: 'text-amber-500',
    bg: 'bg-amber-500/10 border-amber-500/20',
    link: '/leaderboard',
  },
];

const STATS = [
  { label: 'Tests Taken', value: 140000, suffix: '+' },
  { label: 'Users', value: 18000, suffix: '+' },
  { label: 'Avg WPM Gain', value: 30, suffix: '%' },
  { label: 'Tests Daily', value: 3, suffix: ' new' },
];

const TESTIMONIALS = [
  { name: 'Priya S.', role: 'SSC Aspirant', rating: 5, text: "I went from 30 WPM to 55 WPM in just 3 weeks. The structured lessons are exactly what I needed for my government exam prep." },
  { name: 'Rahul K.', role: 'Software Developer', rating: 5, text: "The AI-generated articles keep the practice fresh. I love that there's new content every day — never gets boring." },
  { name: 'Ananya M.', role: 'Data Entry Specialist', rating: 5, text: "Finally achieved 95% accuracy on my exams! The finger placement guides made all the difference for my technique." },
];

export default function HomePage() {
  useEffect(() => {
    document.title = 'FastTypingLab — Learn Typing & Test Your WPM Speed';
  }, []);

  return (
    <div className="bg-brand-bg text-brand-text overflow-x-hidden">

      {/* ── HERO ─────────────────────────────────────────── */}
      <section className="relative min-h-[calc(100dvh-64px)] flex items-center justify-center overflow-hidden px-4 sm:px-6">
        {/* Background gradients */}
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-[-10%] left-[-10%] w-[600px] h-[600px] bg-brand-primary/8 rounded-full blur-[100px]" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[600px] h-[600px] bg-brand-secondary/8 rounded-full blur-[100px]" />
          {/* Subtle dot grid */}
          <div
            className="absolute inset-0 opacity-[0.03]"
            style={{ backgroundImage: 'radial-gradient(circle, currentColor 1px, transparent 1px)', backgroundSize: '24px 24px' }}
          />
        </div>

        <div className="container mx-auto max-w-5xl relative z-10 py-16 sm:py-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center"
          >
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-brand-surface border border-brand-border text-sm font-medium mb-8 text-brand-muted shadow-sm">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-accent opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-brand-accent" />
              </span>
              3 new AI-generated tests added today
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight mb-5 leading-[1.1] text-brand-text">
              Master Typing.{' '}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-primary to-brand-secondary">
                Boost Your Speed.
              </span>
            </h1>

            <p className="text-base sm:text-lg text-brand-text-muted font-light max-w-2xl mx-auto mb-10 leading-relaxed">
              The most complete typing platform for India. Learn touch typing, prep for SSC and government exams,
              and track your WPM in real-time with AI-generated daily content.
            </p>

            {/* CTA buttons */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-14">
              <Link
                to="/tests"
                title="Take a typing speed test"
                className="inline-flex items-center gap-2 bg-brand-primary hover:bg-brand-secondary text-white px-7 py-4 rounded-xl text-base font-bold shadow-lg shadow-brand-primary/25 transition-all duration-200 w-full sm:w-auto justify-center group"
              >
                <Zap className="w-5 h-5" />
                Test Your Speed
                <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
              </Link>
              <Link
                to="/learn"
                title="Start typing lessons"
                className="inline-flex items-center gap-2 bg-brand-surface hover:bg-brand-surface-2 text-brand-text border border-brand-border px-7 py-4 rounded-xl text-base font-bold transition-all duration-200 w-full sm:w-auto justify-center"
              >
                <BookOpen className="w-5 h-5" />
                Start Learning
              </Link>
            </div>

            {/* Live typing preview card */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2, duration: 0.5 }}
              className="max-w-2xl mx-auto bg-brand-surface border border-brand-border rounded-2xl p-5 sm:p-7 shadow-xl text-left relative overflow-hidden"
            >
              <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-brand-primary/40 to-transparent" />
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-rose-400" />
                  <div className="w-2 h-2 rounded-full bg-amber-400" />
                  <div className="w-2 h-2 rounded-full bg-brand-accent" />
                </div>
                <span className="text-xs text-brand-muted font-mono bg-brand-surface-2 px-2.5 py-1 rounded-md">live preview</span>
              </div>
              <TypingPreview />
              <div className="flex items-center gap-6 mt-4 pt-4 border-t border-brand-border">
                <div className="text-center">
                  <div className="text-xs text-brand-muted">WPM</div>
                  <div className="font-black text-brand-primary font-mono">72</div>
                </div>
                <div className="text-center">
                  <div className="text-xs text-brand-muted">Accuracy</div>
                  <div className="font-black text-brand-accent font-mono">98%</div>
                </div>
                <div className="text-center">
                  <div className="text-xs text-brand-muted">CPM</div>
                  <div className="font-black text-brand-text font-mono">360</div>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ── STATS STRIP ─────────────────────────────────── */}
      <section className="bg-brand-surface border-y border-brand-border py-10 px-4 sm:px-6">
        <div className="container mx-auto max-w-4xl grid grid-cols-2 sm:grid-cols-4 gap-8 text-center">
          {STATS.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
            >
              <CountUp to={stat.value} suffix={stat.suffix} />
              <div className="text-xs text-brand-muted font-medium uppercase tracking-wider mt-1">{stat.label}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ────────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6">
        <div className="container mx-auto max-w-5xl">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl sm:text-4xl font-black text-brand-text mb-4">
              Everything you need to type faster
            </h2>
            <p className="text-brand-text-muted max-w-xl mx-auto">
              From beginner lessons to exam preparation — one platform for your entire typing journey.
            </p>
          </motion.div>

          <div className="grid sm:grid-cols-2 gap-5">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
              >
                <Link
                  to={f.link}
                  className="group flex flex-col gap-4 p-6 bg-brand-surface border border-brand-border rounded-2xl hover:border-brand-primary/30 hover:shadow-lg hover:shadow-brand-primary/5 transition-all duration-300 h-full"
                >
                  <div className={`w-11 h-11 rounded-xl flex items-center justify-center border ${f.bg} group-hover:scale-105 transition-transform duration-300`}>
                    <f.icon className={`w-5 h-5 ${f.color}`} />
                  </div>
                  <div className="flex-grow">
                    <h3 className="text-lg font-bold text-brand-text mb-1.5">{f.title}</h3>
                    <p className="text-brand-text-muted text-sm leading-relaxed">{f.desc}</p>
                  </div>
                  <div className={`flex items-center gap-1 text-sm font-semibold ${f.color}`}>
                    Get started <ChevronRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6 bg-brand-surface border-y border-brand-border">
        <div className="container mx-auto max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl sm:text-4xl font-black text-brand-text mb-4">How it works</h2>
          </motion.div>
          <div className="grid sm:grid-cols-3 gap-8 text-center">
            {[
              { n: '01', icon: Keyboard, title: 'Take a test', desc: 'Pick any article or use random words. Timer starts with your first keystroke.' },
              { n: '02', icon: TrendingUp, title: 'See your stats', desc: 'Instantly see WPM, accuracy, CPM, and error breakdown after every session.' },
              { n: '03', icon: Star, title: 'Track progress', desc: 'Your scores are saved. Watch your WPM climb over time and earn achievements.' },
            ].map((step, i) => (
              <motion.div
                key={step.n}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="flex flex-col items-center gap-4"
              >
                <div className="relative">
                  <div className="w-14 h-14 rounded-2xl bg-brand-surface-2 border border-brand-border flex items-center justify-center">
                    <step.icon className="w-6 h-6 text-brand-primary" />
                  </div>
                  <span className="absolute -top-2 -right-2 text-[10px] font-black text-brand-primary bg-brand-surface border border-brand-border rounded-full w-5 h-5 flex items-center justify-center">{step.n}</span>
                </div>
                <h3 className="font-bold text-brand-text">{step.title}</h3>
                <p className="text-brand-text-muted text-sm">{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TESTIMONIALS ────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6">
        <div className="container mx-auto max-w-5xl">
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl sm:text-4xl font-black text-brand-text mb-4">Loved by typists across India</h2>
          </motion.div>
          <div className="grid sm:grid-cols-3 gap-5">
            {TESTIMONIALS.map((t, i) => (
              <motion.div
                key={t.name}
                initial={{ opacity: 0, y: 12 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="bg-brand-surface border border-brand-border rounded-2xl p-6"
              >
                <div className="flex gap-0.5 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} className="w-4 h-4 fill-amber-400 text-amber-400" />
                  ))}
                </div>
                <p className="text-brand-text-muted text-sm leading-relaxed mb-5">"{t.text}"</p>
                <div>
                  <div className="font-bold text-brand-text text-sm">{t.name}</div>
                  <div className="text-brand-muted text-xs">{t.role}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ─────────────────────────────────────────── */}
      <section className="py-20 px-4 sm:px-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.98 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="container mx-auto max-w-3xl bg-gradient-to-br from-brand-primary to-brand-secondary rounded-3xl p-10 sm:p-14 text-center text-white relative overflow-hidden shadow-xl shadow-brand-primary/20"
        >
          <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMSIgY3k9IjEiIHI9IjEiIGZpbGw9InJnYmEoMjU1LDI1NSwyNTUsMC4wOCkiLz48L3N2Zz4=')] pointer-events-none" />
          <h2 className="text-3xl sm:text-4xl font-black mb-4 relative">Start typing smarter today</h2>
          <p className="text-white/80 mb-8 relative max-w-xl mx-auto">
            Join thousands of students and professionals who improved their typing speed with FastTypingLab.
            It's completely free.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 relative">
            <Link
              to="/tests"
              className="inline-flex items-center gap-2 bg-white text-brand-primary hover:bg-white/90 px-8 py-4 rounded-xl font-bold text-base transition-all shadow-lg w-full sm:w-auto justify-center"
            >
              <Zap className="w-5 h-5" /> Take a Free Test
            </Link>
            <Link
              to="/learn"
              className="inline-flex items-center gap-2 bg-white/10 hover:bg-white/20 text-white border border-white/20 px-8 py-4 rounded-xl font-bold text-base transition-all w-full sm:w-auto justify-center"
            >
              <BookOpen className="w-5 h-5" /> Start Lessons
            </Link>
          </div>
        </motion.div>
      </section>

      {/* ── FOOTER LINKS ─────────────────────────────────── */}
      <footer className="border-t border-brand-border py-8 px-4 sm:px-6">
        <div className="container mx-auto max-w-5xl flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <span className="w-7 h-7 rounded-lg bg-brand-primary text-white flex items-center justify-center font-black text-sm">T</span>
            <span className="font-bold text-brand-text">FastTypingLab</span>
          </div>
          <div className="flex flex-wrap gap-4 text-sm text-brand-muted">
            <Link to="/learn" className="hover:text-brand-primary transition-colors">Learn Typing</Link>
            <Link to="/tests" className="hover:text-brand-primary transition-colors">Speed Tests</Link>
            <Link to="/leaderboard" className="hover:text-brand-primary transition-colors">Leaderboard</Link>
            <a href="mailto:support@fasttypinglab.com" className="hover:text-brand-primary transition-colors">Contact</a>
          </div>
          <p className="text-xs text-brand-muted w-full sm:w-auto text-center sm:text-right">© 2026 FastTypingLab. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
